---
test:
  clients:
    type: local
    number: 5
  rounds:
  - label: init
    txNumber:
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    - 10000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 50
    - type: fixed-rate
      opts:
        tps: 100
    - type: fixed-rate
      opts:
        tps: 150
    - type: fixed-rate
      opts:
        tps: 200
    - type: fixed-rate
      opts:
        tps: 250
    - type: fixed-rate
      opts:
        tps: 300
    - type: fixed-rate
      opts:
        tps: 350
    - type: fixed-rate
      opts:
        tps: 400
    - type: fixed-rate
      opts:
        tps: 500
    - type: fixed-rate
      opts:
        tps: 600
    callback: benchmark/marbles/init.js
  - label: query
    txNumber:
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 100
    - type: fixed-rate
      opts:
        tps: 200
    - type: fixed-rate
      opts:
        tps: 300
    - type: fixed-rate
      opts:
        tps: 400
    - type: fixed-rate
      opts:
        tps: 500
    - type: fixed-rate
      opts:
        tps: 600
    - type: fixed-rate
      opts:
        tps: 700
    - type: fixed-rate
      opts:
        tps: 800
    - type: fixed-rate
      opts:
        tps: 900
    callback: benchmark/marbles/query.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
