---
test:
  name: smallbank
  description: This is smallbank benchmark for caliper
  clients:
    type: local
    number: 5
  rounds:
  - label: smallOperations
    txDuration:
    - 900
    rateControl:
    - type: fixed-rate
      opts:
        tps: 650
    arguments:
      accounts: 100000
      txnPerBatch: 1
    callback: benchmark/smallbank/smallbankOperations.js
monitor:
  type: docker
  docker:
    name:
    - all
  interval: 1
